### ISSUE TITLE
KV: getWithMetadata: Method not implemented

### ISSUE THREAD

**Issue by ccremer** [chientrm/wrangler-proxy#6]
Hi.
Just trying out this repo. It looks like that KV proxy isn't fully implemented

```
Error: Method not implemented.
    at v.getWithMetadata (file:///.../node_modules/wrangler-proxy/dist/index.js:1:9379)
```

**Comment by chientrm** [comment]
> Hi.
> Just trying out this repo. It looks like that KV proxy isn't fully implemented
> 
> ```
> Error: Method not implemented.
>     at v.getWithMetadata (file:///.../node_modules/wrangler-proxy/dist/index.js:1:9379)
> ```

Working on it 💪
